# Site settings
title: Bulent Guneralp
email: bulent@bulentguneralp.com
description: "Bulent Guneralp is a Boston-area singer, pianist, drummer, and instructor. He has 10 years of experience teaching music and offers lessons from his studio in Somerville."
baseurl: ""
url: "http://www.bulentguneralp.com"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
