# Site settings
title: Bülent Güneralp
email: bulent@bulentguneralp.com
description: "A Boston-area singer, pianist, drummer, and instructor with over 18 years of experience teaching music. Lessons are available at my studio in Somerville, MA."
baseurl: ""
url: "http://www.bulentguneralp.com"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass

