# Site settings
title: Bulent Guneralp
email: bulent@bulentguneralp.com
description: "I'm a Boston-area singer, pianist, drummer, and instructor. I have 10 years of experience teaching music and offer lessons from my studio in Somerville."
baseurl: ""
url: "http://www.bulentguneralp.com"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
