# Site settings
title: Bülent Güneralp
email: bulent@bulentguneralp.com
description: "An active Boston-area singer, pianist, and instructor with over 18 years of experience teaching music. Lessons are available at my studio in Somerville, MA."
baseurl: ""
url: "http://www.bulentguneralp.com"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass

